apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
        - name: nginx
          image:  nginx:1.19.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80